root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"  # Linux下无需.exe后缀
# macOS 本机编译命令
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "vendor", "docs", "frontend", "client",".idea"]
exclude_file = []
exclude_regex = []
include_ext = ["go", "tpl", "tmpl"]
log = "build-errors.log"
color = true

[misc]
clean_on_exit = true
