/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'class',
    path: '/class',
    component: 'layout.base$view.class',
    meta: {
      title: 'class',
      i18nKey: 'route.class',
      icon: 'mdi:google-classroom',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'leave-record',
    path: '/leave-record',
    component: 'layout.base$view.leave-record',
    meta: {
      title: 'leave-record',
      i18nKey: 'route.leave-record',
      icon: 'mdi:clipboard-text-clock-outline',
      order: 3
    }
  },
  {
    name: 'leave-type',
    path: '/leave-type',
    component: 'layout.base$view.leave-type',
    meta: {
      title: 'leave-type',
      i18nKey: 'route.leave-type',
      icon: 'mdi:format-list-bulleted',
      order: 5
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'student',
    path: '/student',
    component: 'layout.base$view.student',
    meta: {
      title: 'student',
      i18nKey: 'route.student',
      icon: 'mdi:account-school',
      order: 2
    }
  }
];
